name: update-contract

on:
  schedule:
    - cron:  '*/45 * * * *'

  workflow_dispatch:


concurrency:
  group: one


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 240


    steps:

      - name: Prepare
        run: sleep 10s
        shell: bash


      - name: Checkout
        uses: actions/checkout@v2


      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          

      - name: Install dependencies
        run: pip3 install -r requirements.txt
        working-directory: utils


      - name: Update CURRENT_BLOCK
        run: python3 run.py update
        working-directory: utils
    

      - name: Commit CURRENT_BLOCK
        uses: EndBug/add-and-commit@v7
        with:
          add: '.'
          message: 'update blocknumber'


      - name: Dump Contracts
        run: python3 run.py
        working-directory: utils
    

      - name: Autocommit
        uses: EndBug/add-and-commit@v7
        with:
          add: '.'
          message: 'autocommit'
